
baseURL = "https://www.learnerprivacy.org/"
languageCode = "en-us"
title = "LearnerPrivacy.org"
theme = "lp-dream"
author = "Charles R. Severance"

[params]
  # background = "black"
  # backgroundImage = "/me/high-rise-buildings-at-nighttime-2147287.jpg"
  # backgroundImage = "/me/greyscale-photography-of-person-walking-between-trees-3304855.jpg"
  # backgroundImage = "/me/group-of-people-crossing-pedestrian-lane-in-greyscale-1309687.jpg"
  backgroundImage = "/me/low-angle-view-of-man-standing-at-night-316681.jpg"
  splashImage = "/me/splashimage.png"
  darkNav = true
  author = "Learner Privacy"
  motto = "Protecting Learner Data"
  avatar = "/me/learnerprivacy-org-avatar-light.png"
  avatar_dark = "/me/learnerprivacy-org-avatar-dark.png"
  email = "learnerprivacy@learnxp.com"
  facebook = "LearnerPrivacy"
  patreon = "learnerprivacy"
  twitter = "drchuck"
  # github = "LearnerPrivacy"
  # stackoverflow = "1994792/drchuck"
  podcast = "https://podcast.learnerprivacy.org"
  linkedin = "charlesseverance"
