
baseURL = "https://www.learnerprivacy.org/"
languageCode = "en-us"
title = "LearnerPrivacy.org"
theme = "lp-dream"

[params]
  # background = "black"
  backgroundImage = "/me/high-rise-buildings-at-nighttime-2147287.jpg"
  darkNav = true
  author = "Learner Privacy"
  name = "Learner Privacy"
